version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-tareas
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tareasdb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: